document.writeln("<div class=\'container\'>");
document.writeln("            <nav class=\'navbar fixed-top navbar-expand-lg navbar-dark bg-dark\'>");
document.writeln("                <a class=\'navbar-brand\' href=\'/\'>GokazeACG</a>");
document.writeln("                <button class=\'navbar-toggler collapsed\' type=\'button\' data-toggle=\'collapse\'");
document.writeln("                    data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\'");
document.writeln("                    aria-label=\'Toggle navigation\'>");
document.writeln("                    <span class=\'navbar-toggler-icon\'></span>");
document.writeln("                </button>");
document.writeln("                <div class=\'navbar-collapse collapse\' id=\'navbarSupportedContent\'>");
document.writeln("                    <ul class=\'navbar-nav mr-auto\'>");
document.writeln("                        <li class=\'nav-item active\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/202001/index.html\'>2020冬番</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item active\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/202004/index.html\'>2020春番</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item active\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/202007/index.html\'>2020夏番</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item active\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/202010/index.html\'>2020秋番</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item dropdown\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/old/index.html\'>舊番</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/Q&A.html\'>Q&amp;A</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a class=\'nav-link\' href=\'mailto:gokazeacg@gmail.com\'>聯繫我</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a class=\'nav-link\' href=\'/easteregg.html\' tabindex=\'-1\' aria-disabled=\'false\'>舉報</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </nav>");
document.writeln("        </div>");