document.writeln("<select class=\'form-control\' style=\'background-color: black; width: 150px;\' onchange=\'week(this)\'>");
document.writeln("                <option value=\'all\' selected>選擇播放時間</option>");
document.writeln("                <option value=\'mon\'>周一</option>");
document.writeln("                <option value=\'tue\'>週二</option>");
document.writeln("                <option value=\'wen\'>週三</option>");
document.writeln("                <option value=\'thi\'>週四</option>");
document.writeln("                <option value=\'fri\'>週五</option>");
document.writeln("                <option value=\'sat\'>週六</option>");
document.writeln("                <option value=\'sun\'>週日</option>");
document.writeln("            </select>");
document.writeln("            <script type=\'text/javascript\'>");
document.writeln("                function week(value) {");
document.writeln("                    var selectedOption = value.options[value.selectedIndex];");
document.writeln("                    //alert(selectedOption.value);");
document.writeln("                    if (selectedOption.value == \'mon\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    }");
document.writeln("                    else if (selectedOption.value == \'tue\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    } else if (selectedOption.value == \'wen\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    } else if (selectedOption.value == \'thi\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    } else if (selectedOption.value == \'fri\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    } else if (selectedOption.value == \'sat\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'none\';");
document.writeln("                    } else if (selectedOption.value == \'all\') {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'unset\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'unset\';");
document.writeln("                    } else {");
document.writeln("                        document.getElementById(\'monday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'tuesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'wednesday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'thirsday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'friday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'saturday\').style.display = \'none\';");
document.writeln("                        document.getElementById(\'sunday\').style.display = \'unset\';");
document.writeln("                    }");
document.writeln("                };");
document.writeln("            </script>");